### ISSUE TITLE
Set Lua package.path and package.cpath to include LuaRocks package

### ISSUE THREAD

**Issue by Stratus3D** [smashedtoatoms/asdf-luaJIT#1]
I created an exec-env file in asdf-lua to set the `LUA_INIT` environment variable so these paths are set (https://github.com/Stratus3D/asdf-lua/blob/master/bin/exec-env). This was discussed here: https://github.com/Stratus3D/asdf-lua/pull/2

**Comment by smashedtoatoms** [comment]
Cool.  I haven't had a chance to do this yet.  I will get to it as soon as I can.
