### ISSUE TITLE
Cannot build LuaRocks in kubuntu 18.0.4

### ISSUE THREAD

**Issue by lh-latif** [smashedtoatoms/asdf-luaJIT#4]
Hi,
I trying to install luaJIT in kubuntu 18.0.4, when it start to build and install luaJIT it was go with flawless, then in return error when it trying to build LuaRocks. it says *no rule to make target "build"*. so i change code in install files. Then in building luarocks section, i change "make build || exit 1" to "make || exit 1".
thanks

**Comment by smashedtoatoms** [comment]
I am SO sorry.  I just saw this.  It has been updated.
