### ISSUE TITLE
Does not build on MacOS

### ISSUE THREAD

**Issue by cmaher** [smashedtoatoms/asdf-luaJIT#7]
At least on Catalina, lua JIT does not compile.

`asdf install luaJIT 2.1.0-beta3--3.4.0`

It exits with
```
Undefined symbols for architecture x86_64:
  "__Unwind_DeleteException", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_GetCFA", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_RaiseException", referenced from:
      _lj_err_throw in libluajit.a(lj_err.o)
  "__Unwind_SetGR", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_SetIP", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected behavior**

luaJIT compiles and is installed.

**Additional context**
[LuaJIT is no longer setting a default MAC_OSX_DEPLOYMENT_TARGET.](https://github.com/LuaJIT/LuaJIT/issues/484) 
I addressed this by running  `MACOSX_DEPLOYMENT_TARGET=10.6 DEFAULT_CC=clang asdf install luaJIT 2.1.0-beta3--3.4.0`

**Comment by ELLIOTTCABLE** [comment]
I'm also unable to build this; my error is slightly different — the ` MACOSX_DEPLOYMENT_TARGET=10.13 DEFAULT_CC=clang` didn't help:

```
Building luaJIT with options:  PREFIX=/Users/ec/.local/share/rtx/installs/luaJIT/2.0.5--2.4.4
==== Building LuaJIT 2.0.5 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
lj_arch.h:55:2: error: "No support for this architecture (yet)"
#error "No support for this architecture (yet)"
 ^
lj_arch.h:294:2: error: "No target architecture defined"
#error "No target architecture defined"
 ^
lj_arch.h:317:2: error: "Need at least GCC 4.3 or newer"
#error "Need at least GCC 4.3 or newer"
 ^
3 errors generated.
```

**Comment by smashedtoatoms** [comment]
I haven't used luaJIT in quite some time, and it appears that whatever version of GCC you're on and whatever version of luaJIT you're on isn't compatible with the latest mac architecture.  I will see if I can carve out some time to look at this, but it likely won't be until after next weekend.

**Comment by smashedtoatoms** [comment]
I have not idea why I didn't see this until today.  I am really sorry, everyone.

**Comment by smashedtoatoms** [comment]
I updated the README and approved some PRs that address this.  I am able to get this running on arm macs now.
